services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - DOCS_URL=${DOCS_URL:-/api}
    env_file:
      - .env
